<a href="https://colab.research.google.com/github/AnhelinaKavaliova/task2/blob/main/assignment_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
np.random.seed(0)
arr = np.random.randint(0, 10, 10)
print("Original array: ", arr)

serach_ind = (arr > 3) & (arr < 8)
arr[serach_ind] = -arr[serach_ind]
print("Result: ", arr)

Original array:  [5 0 3 3 7 9 3 5 2 4]
Result:  [-5  0  3  3 -7  9  3 -5  2 -4]


**2.** Заменить максимальный элемент случайного массива на 0

In [ ]:
arr[arr.argmax()] = 0
print(arr)

[-5  0  3  3 -7  0  3 -5  2 -4]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [ ]:
np.random.seed(24)
array = np.random.randint(0, 10, size=(2, 2))
print("Original array: \n", array)

result = np.array(np.meshgrid(*array)).T.reshape(-1, 2)
print("Result: \n", result)

Original array: 
 [[2 3]
 [0 7]]
Result: 
 [[2 0]
 [2 7]
 [3 0]
 [3 7]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [ ]:
A = np.random.randint(0, 4, size=(8, 3))
B = np.random.randint(0, 4, size=(2, 2))

print("Array A:\n", A)
print("Array B:\n", B)

rows_B = [set(row) for row in B]
matching_rows = []

for row in A:
  row_A = set(row)
  if all(row_A.issuperset(b_set) for b_set in rows_B):
    matching_rows.append(row)

matching_rows = np.array(matching_rows)
print("Result:\n", matching_rows)
print(matching_rows)

Array A:
 [[1 1 1]
 [0 3 3]
 [0 3 3]
 [2 3 3]
 [3 3 3]
 [3 1 2]
 [3 3 1]
 [3 1 3]]
Array B:
 [[0 0]
 [2 0]]
Result:
 []
[]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [ ]:
matrix = np.random.randint(0, 2, size=(10, 3))
print("Original matrix: \n", matrix)

#res = np.array([row for row in matrix if len(set(row)) > 1])
unique_rows_elements_num = np.apply_along_axis(lambda row: len(np.unique(row)), 1, matrix)
res = matrix[unique_rows_elements_num > 1]
print("Result: \n", res)

Original matrix: 
 [[1 1 1]
 [0 1 0]
 [1 1 0]
 [0 1 0]
 [1 1 0]
 [1 0 0]
 [1 1 1]
 [1 0 1]
 [0 0 1]
 [0 1 1]]
Result: 
 [[0 1 0]
 [1 1 0]
 [0 1 0]
 [1 1 0]
 [1 0 0]
 [1 0 1]
 [0 0 1]
 [0 1 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [ ]:
array = np.random.randint(0, 2, size = (5, 3))
print("Original array: \n", array)

unique_rows = np.unique(array, axis=0)
print("Result: \n", unique_rows)

Original array: 
 [[1 0 1]
 [0 0 1]
 [0 0 1]
 [1 0 1]
 [0 0 1]]
Result: 
 [[0 0 1]
 [1 0 1]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [ ]:
matrix = [
    [1, 0, 1],
    [2, 0, 2],
    [3, 0, 3],
    [4, 4, 4]
]

In [ ]:
rows = len(matrix)
cols = len(matrix[0])
result = 1

for i in range(min(rows, cols)):
  if matrix[i][i] != 0:
    result *= matrix[i][i]

print("Result:", result)

Result: 3


In [ ]:
#numpy
X = np.array([[1, 0, 1],
              [2, 0, 2],
              [3, 0, 3],
              [4, 4, 4]])

In [ ]:
diagonal = np.diagonal(X)
result = np.prod(diagonal[diagonal != 0])

print("Result:", result)

Result: 3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [ ]:
x_py = [1, 2, 2, 4]
y_py = [4, 2, 1, 2]

In [ ]:
answer = sorted(x_py) == sorted(y_py)
print("Answer: ", answer)

Answer:  True


In [ ]:
#numpy
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

In [ ]:
answer = np.array_equal(np.sort(x), np.sort(y))
print("Answer: ", answer)

Answer:  True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль.
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [ ]:
x_py = [6, 2, 0, 3, 0, 0, 5, 7, 0]

In [ ]:
max_el = None
for i in range(1, len(x_py)):
  if x_py[i-1] == 0 and (max_el is None or max_el < x_py[i]):
    max_el = x_py[i]

print("Answer: ", max_el)

Answer:  5


In [ ]:
#numpy
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

In [ ]:
null_el_ind = np.where(x == 0)[0]
valid_ind = null_el_ind[null_el_ind + 1 < len(x)]
following_elements = x[valid_ind+1]
print("Answer: ", np.max(following_elements))

Answer:  5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [2]:
x_py = [2, 4, 2, 3, 3, 3, 5]

In [3]:
from itertools import groupby

elements = []
el_count = []

for k, g in groupby(x_py):
  elements.append(k)
  el_count.append(len(list(g)))

elements, el_count

([2, 4, 2, 3, 5], [1, 1, 1, 3, 1])

In [4]:
#numpy
x = np.array([2, 4, 2, 3, 3, 3, 5])

In [5]:
new_el = np.concatenate(([True], x[1:] != x[:-1]))
indices = np.nonzero(new_el)[0]
elements = x[indices]
el_count = np.diff(np.concatenate((indices, [len(x)])))

elements, el_count

(array([2, 4, 2, 3, 5]), array([1, 1, 1, 3, 1]))

* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [ ]:
X_py = [[1, 2], [3, 4], [9, 10]]
Y_py = [[5, 6], [7, 8]]

In [ ]:
import time
from math import sqrt

start_time = time.time()
distances = [[0] * len(Y_py) for _ in range(len(X_py))]
for i, x in enumerate(X_py):
        for j, y in enumerate(Y_py):
            distances[i][j] = sqrt(sum((xi - yi) ** 2 for xi, yi in zip(x, y)))

end_time = time.time()

print("Distance matrix:\n", distances)
print("Execution time (without numpy):", end_time - start_time)


Distance matrix:
 [[5.656854249492381, 8.48528137423857], [2.8284271247461903, 5.656854249492381], [5.656854249492381, 2.8284271247461903]]
Execution time (without numpy): 0.0002903938293457031


In [ ]:
#numpy
X = np.array([[1, 2], [3, 4], [9, 10]])
Y = np.array([[5, 6], [7, 8]])

In [ ]:
start_time = time.time()
distances = np.sqrt(np.sum((X[:, np.newaxis] - Y) ** 2, axis=-1))
end_time = time.time()
print("Distance matrix:\n", distances)
print("Execution time (with numpy):", end_time - start_time)

Distance matrix:
 [[5.65685425 8.48528137]
 [2.82842712 5.65685425]
 [5.65685425 2.82842712]]
Execution time (with numpy): 0.0003800392150878906


In [ ]:
from scipy.spatial.distance import cdist

start_time = time.time()
distances_scipy = cdist(X, Y, metric='euclidean')
end_time = time.time()

print("Distance matrix (scipy):\n", distances_scipy)
print("Execution time (scipy cdist):", end_time - start_time)


Distance matrix (scipy):
 [[5.65685425 8.48528137]
 [2.82842712 5.65685425]
 [5.65685425 2.82842712]]
Execution time (scipy cdist): 0.0003712177276611328


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [ ]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [ ]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [ ]:
crunchie_munchies_calories = 60

In [ ]:
average_calories = np.average(calorie_stats)
print("Average calories: ", average_calories)
print("Difference: ", average_calories - crunchie_munchies_calories)

Average calories:  106.88311688311688
Difference:  46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [ ]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [ ]:
median_calories = np.median(calorie_stats_sorted)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [ ]:
for p in range(1, 101):
  percentile_value = np.percentile(calorie_stats_sorted, p)
  if percentile_value > 60:
      nth_percentile = p
      break

nth_percentile

4

In [ ]:
left, right = 0, 100
nth_percentile = None

while left < right:
  mid = (left + right) // 2
  percentile_value = np.percentile(calorie_stats_sorted, mid)

  if percentile_value > 60:
    right = mid
    nth_percentile = mid
  else:
    left = mid + 1

nth_percentile

4

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [ ]:
more_calories = [cal for cal in calorie_stats_sorted if cal > 60]
more_calories = (len(more_calories)/len(calorie_stats_sorted))*100
more_calories

96.1038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [ ]:
calorie_std = np.std(calorie_stats_sorted)
calorie_std

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

Среднее количество калорий в злаках конкурентов значительно выше, чем в CrunchieMunchies, медиана и процентили также говорят, что большинство конкурентов имеют больше калорий, что подчеркивает преимущество CrunchieMunchies с точки зрения калорийности.Данные можно использовать в маркетинге для подчеркивания низкого содержания калорий CrunchieMunchies, что делает продукт привлекательным выбором для потребителей, стремящихся к пп